# Generated by Django 6.0.5 on 2026-06-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_watchparty_scheduled_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='subtitle_url',
            field=models.URLField(blank=True),
        ),
    ]
