# Generated by Django 6.0.5 on 2026-06-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0003_videosession_subtitle_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='poster_url',
            field=models.URLField(blank=True),
        ),
    ]
