# Generated by Django 6.0.5 on 2026-06-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='subtitle_file',
            field=models.FileField(blank=True, null=True, upload_to='subtitles/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='subtitle_url',
            field=models.URLField(blank=True, help_text='External .vtt URL'),
        ),
    ]
