# Generated by Django 6.0.5 on 2026-06-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_movie_subtitle_file_movie_subtitle_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='transcode_status',
            field=models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing'), ('failed', 'Failed')], default='ready', max_length=12),
        ),
    ]
