# Generated by Django 6.0.5 on 2026-06-03 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_movie_transcode_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tmdb_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='MovieRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(blank=True, max_length=8)),
                ('overview', models.TextField(blank=True)),
                ('poster_url', models.URLField(blank=True)),
                ('backdrop_url', models.URLField(blank=True)),
                ('vote_count', models.PositiveIntegerField(db_index=True, default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Optional admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.movie')),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_requests', to=settings.AUTH_USER_MODEL)),
                ('voters', models.ManyToManyField(blank=True, related_name='movie_requests_voted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-vote_count', '-created_at'],
            },
        ),
    ]
