# Generated by Django 6.0.5 on 2026-06-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_movie_tmdb_data_movierequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='movierequest',
            name='estimated_size_mb',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
